// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/jasontest/jasontest.proto

package go_micro_srv_jasontest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Jasontest service

type JasontestService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Jasontest_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Jasontest_PingPongService, error)
}

type jasontestService struct {
	c    client.Client
	name string
}

func NewJasontestService(name string, c client.Client) JasontestService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.jasontest"
	}
	return &jasontestService{
		c:    c,
		name: name,
	}
}

func (c *jasontestService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Jasontest.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasontestService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Jasontest_StreamService, error) {
	req := c.c.NewRequest(c.name, "Jasontest.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &jasontestServiceStream{stream}, nil
}

type Jasontest_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type jasontestServiceStream struct {
	stream client.Stream
}

func (x *jasontestServiceStream) Close() error {
	return x.stream.Close()
}

func (x *jasontestServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *jasontestServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *jasontestServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jasontestService) PingPong(ctx context.Context, opts ...client.CallOption) (Jasontest_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Jasontest.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &jasontestServicePingPong{stream}, nil
}

type Jasontest_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type jasontestServicePingPong struct {
	stream client.Stream
}

func (x *jasontestServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *jasontestServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *jasontestServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *jasontestServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *jasontestServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Jasontest service

type JasontestHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Jasontest_StreamStream) error
	PingPong(context.Context, Jasontest_PingPongStream) error
}

func RegisterJasontestHandler(s server.Server, hdlr JasontestHandler, opts ...server.HandlerOption) error {
	type jasontest interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Jasontest struct {
		jasontest
	}
	h := &jasontestHandler{hdlr}
	return s.Handle(s.NewHandler(&Jasontest{h}, opts...))
}

type jasontestHandler struct {
	JasontestHandler
}

func (h *jasontestHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.JasontestHandler.Call(ctx, in, out)
}

func (h *jasontestHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.JasontestHandler.Stream(ctx, m, &jasontestStreamStream{stream})
}

type Jasontest_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type jasontestStreamStream struct {
	stream server.Stream
}

func (x *jasontestStreamStream) Close() error {
	return x.stream.Close()
}

func (x *jasontestStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *jasontestStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *jasontestStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *jasontestHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.JasontestHandler.PingPong(ctx, &jasontestPingPongStream{stream})
}

type Jasontest_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type jasontestPingPongStream struct {
	stream server.Stream
}

func (x *jasontestPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *jasontestPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *jasontestPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *jasontestPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *jasontestPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
